"""initial

Revision ID: 282f2fbf0350
Revises: 
Create Date: 2026-02-27 13:33:32.193931
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '282f2fbf0350'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('business_type', sa.Enum('service', 'retail', 'manufacturing', 'trading', 'professional', name='business_type_enum'), nullable=True),
    sa.Column('return_frequency', sa.Enum('monthly', 'quarterly', name='return_frequency_enum'), nullable=False),
    sa.Column('fy_start_month', sa.Integer(), nullable=False),
    sa.Column('tax_regime', sa.Enum('new', 'old', name='tax_regime_enum'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_table('aggregate_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('cache_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cache_key', name='uq_aggregate_cache_key')
    )
    op.create_index(op.f('ix_aggregate_cache_tenant_id'), 'aggregate_cache', ['tenant_id'], unique=False)
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='account_type_enum'), nullable=False),
    sa.Column('tally_group', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_cash_or_bank', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_deleted_at'), 'chart_of_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chart_of_accounts_tenant_id'), 'chart_of_accounts', ['tenant_id'], unique=False)
    op.create_table('gst_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('monthly', 'quarterly', name='gst_period_type_enum'), nullable=False),
    sa.Column('output_cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('output_sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('output_igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('output_cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('input_cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period_start', 'period_type', name='uq_gst_summary_period')
    )
    op.create_index(op.f('ix_gst_summaries_tenant_id'), 'gst_summaries', ['tenant_id'], unique=False)
    op.create_table('it_estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_regime', sa.Enum('new', 'old', name='it_regime_enum'), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estimated_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_tax_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slab_breakup', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fy', name='uq_it_estimate_fy')
    )
    op.create_index(op.f('ix_it_estimates_tenant_id'), 'it_estimates', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cognito_sub', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('owner', 'accountant', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_tenant_time', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_version_id', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.Enum('invoice', 'credit_note', 'debit_note', 'receipt', name='document_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED', 'VALIDATED', 'FAILED', 'DONE', name='document_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_tenant_status', 'documents', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_table('canonical_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('invoice', 'credit_note', 'debit_note', 'receipt', name='invoice_doc_type_enum'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_gstin', sa.String(length=15), nullable=True),
    sa.Column('vendor_state_code', sa.String(length=2), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('buyer_state_code', sa.String(length=2), nullable=True),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_invoice_id', sa.UUID(), nullable=True),
    sa.Column('original_invoice_number', sa.String(length=100), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('duplicate_hash', sa.String(length=64), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALID', 'INVALID', 'APPROVED', 'REJECTED', name='invoice_validation_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['canonical_invoices.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['canonical_invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoices_duplicate_hash', 'canonical_invoices', ['tenant_id', 'duplicate_hash'], unique=True)
    op.create_index('idx_invoices_tenant_date', 'canonical_invoices', ['tenant_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_canonical_invoices_deleted_at'), 'canonical_invoices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_canonical_invoices_document_id'), 'canonical_invoices', ['document_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('raw_textract_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('canonical_invoice_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AUTO_POSTED', 'NEEDS_REVIEW', 'CORRECTED', 'REVERSED', name='txn_status_enum'), nullable=False),
    sa.Column('reverses_transaction_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('assigned_category', sa.String(length=100), nullable=True),
    sa.Column('category_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('category_method', sa.Enum('rule', 'bedrock', 'manual', name='category_method_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_invoice_id'], ['canonical_invoices.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reverses_transaction_id'], ['ledger_transactions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_tenant_date', 'ledger_transactions', ['tenant_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_deleted_at'), 'ledger_transactions', ['deleted_at'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('field_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_status', sa.Enum('pass', 'fail', 'warn', name='validation_status_enum'), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('validated_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_document_id'), 'validations', ['document_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_transaction_id'), 'corrections', ['transaction_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit >= 0', name='ck_credit_positive'),
    sa.CheckConstraint('debit >= 0', name='ck_debit_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_transaction', 'journal_lines', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_journal_transaction', table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_corrections_transaction_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_validations_document_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_ledger_transactions_deleted_at'), table_name='ledger_transactions')
    op.drop_index('idx_ledger_tenant_date', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_canonical_invoices_document_id'), table_name='canonical_invoices')
    op.drop_index(op.f('ix_canonical_invoices_deleted_at'), table_name='canonical_invoices')
    op.drop_index('idx_invoices_tenant_date', table_name='canonical_invoices')
    op.drop_index('idx_invoices_duplicate_hash', table_name='canonical_invoices')
    op.drop_table('canonical_invoices')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index('idx_documents_tenant_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_audit_tenant_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_it_estimates_tenant_id'), table_name='it_estimates')
    op.drop_table('it_estimates')
    op.drop_index(op.f('ix_gst_summaries_tenant_id'), table_name='gst_summaries')
    op.drop_table('gst_summaries')
    op.drop_index(op.f('ix_chart_of_accounts_tenant_id'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_deleted_at'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    op.drop_index(op.f('ix_aggregate_cache_tenant_id'), table_name='aggregate_cache')
    op.drop_table('aggregate_cache')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
