"""add_content_hash_to_documents

Revision ID: 6d59cfd1d696
Revises: 8d4f2a1b3c5e
Create Date: 2026-03-09 11:51:12.850967
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6d59cfd1d696'
down_revision: Union[str, None] = '8d4f2a1b3c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
