"""widen_coa_code_column

Revision ID: 7cf9e6368b62
Revises: 13165e09531a
Create Date: 2026-02-27 13:36:50.419911
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7cf9e6368b62'
down_revision: Union[str, None] = '13165e09531a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart_of_accounts', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart_of_accounts', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
